Change updateAdventureDisplay calls
While testing if adventure still works after the past few refactors, I
ran into this error:

	TypeError: adventureManager.updateAdventureDisplay is not a
	function

I apparently forgot to change the call statements from
updateAdventureDisplay to updateDisplay when I changed the function
name.

It's 5 in the morning OK.