Add missing let declaration for abilityButton
The abilityButton variable in AdventureManager's updateAbilityUI is
missing a let declaration. I am not exactly sure why and how it used to
work. After merging updateAbilityUI to AdventureManager, it now throws
the following error:

	ReferenceError: abilityButton is not defined